### PR TITLE
feat: Add exclusive_jets_up_to() interface

### LINKED ISSUE #219: exclusive_jets_up_to()
It would be very useful to expose the functionality of ClusterSequence::exclusive_jets_up_to() in the awkward/multievent interface. I see that exclusive_subjets_up_to is implemented, so I assume it is possible and maybe even easy if that function can be partly copied.

I was prepared to try and implement it myself, but unfortunately I burned all the time I had budgeted for this fighting with the build system. Currently setup.py overwrites CXXFLAGS and LDFLAGS so there is no easy way to pass nonstandard include/lib dirs. That's a pretty easy fix, but the real limitation is fj-contrib's very poor build system, which hardcodes g++ instead of using $(CXX) and doesn't use LDFLAGS at all. At that point I gave up :/

### PR DESCRIPTION
**Pull request by jmduarte**
resolves #219 

@cshimmin

### CODE REVIEW

**Comment by jmduarte** [comment]
@cshimmin can you try pip installing one of these wheels (non-m1/m2 mac os x or linux): https://github.com/scikit-hep/fastjet/suites/13455142622/artifacts/738101752 to see if you can use `cluster.exclusive_jets_up_to(n_jets)` for your use case?

**Comment by cshimmin** [comment]
Hi Javier,
Thanks, just saw this. Will give it a go tonight and let you know!

Cheers,
-Chase

**Comment by lgray** [comment]
@cshimmin lemme know if you find any problems and I'll approve, codewise it's fine.

**Comment by lgray** [comment]
@cshimmin ping :-)

**Review by lgray — APPROVED** [review]

**Pull request merged**
