### PR TITLE
ci: fix failing tests after update to upload-artifact v4

### PR DESCRIPTION
**Pull request by chrispap95**
upload-artifact v4 cannot overwrite artifacts and this causes the tests to fail.

### CODE REVIEW

**Comment by chrispap95** [comment]
So it fixes the overwrite issue in the CI wheel tests. The real question is if it handles correctly the full wheel building process. Perhaps someone more knowledgeable should take a look at these changes.

**Comment by lgray** [comment]
I personally don't use this action so I'm not sure if this will be correct.

**Review by matthewfeickert — COMMENTED** [review]
Sorry, I don't have time to give a full useful review right this minute, but I can at least point you to https://github.com/scientific-python/cookie/pull/350 which should show how to simplify things a bit.

Just make sure that both the upload and download are **both** on v4 or you'll have problems.

**Comment by chrispap95** [comment]
I implemented the changes as they are suggested in https://github.com/scientific-python/cookie/pull/350
I quite confident they are okay. I will merge tonight if there no objections.

**Review by matthewfeickert — APPROVED** [review]
LGTM. :+1: Things are passing, so I'd say hit it! :rocket:

**Pull request merged**
